### ISSUE TITLE
Throw an exception in case of a fault

### ISSUE THREAD

**Issue by sagikazarmark** [fxmlrpc/serialization#6]
@lstrojny can you tell me why you chose passing a variable by reference to determine if the request is a fault or not? I guess there was a reason for that.

IMO throwing a fault exception would be somewhat better. WDYT?

**Comment by lstrojny** [comment]
Agreed, fixed in the combined repository in https://github.com/lstrojny/fxmlrpc/commit/3079f5cf1c839f601e1a88b97dbe77c75295014a
